### ISSUE TITLE
Thumbnail generation direction is wrong

### ISSUE THREAD

**Issue by tumayun** [dirkvdb/ffmpegthumbnailer#130]
Thumbnail generation direction is wrong.

### Command

```shell
ffmpegthumbnailer -i 42C064A5-5213-473D-B9B2-CD4DFA7FAAE2.mp4 -o 1.jpg -s 320 -t 00:00:00 -q 5
```
### Video
https://s3.cn-north-1.amazonaws.com.cn/ruanwz-test/42C064A5-5213-473D-B9B2-CD4DFA7FAAE2.mp4

### Thumbnail
![1](https://cloud.githubusercontent.com/assets/1154724/13520270/f220c0da-e219-11e5-98f9-f54bc8f8a765.jpg)

**Comment by dirkvdb** [comment]
It seems like I will need to take into account the rotate metadata

**Comment by dirkvdb** [comment]
It just pushed fix that should respect the rotation metadata when generating a thumb

**Comment by tumayun** [comment]
@dirkvdb 
Thank you very much for your help!
I need to install the latest ffmpegthumbnailer (master branch) in the server, how should I do?

I encountered the following error in the installation：
```shell
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
AVCODEC_INCLUDE_DIR
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master/test
AVCODEC_LIBRARY
    linked by target "libffmpegthumbnailer" in directory /home/deploy/ffmpegthumbnailer-master
    linked by target "libffmpegthumbnailerstatic" in directory /home/deploy/ffmpegthumbnailer-master
AVFILTER_INCLUDE_DIR
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master/test
AVFILTER_LIBRARY
    linked by target "libffmpegthumbnailer" in directory /home/deploy/ffmpegthumbnailer-master
    linked by target "libffmpegthumbnailerstatic" in directory /home/deploy/ffmpegthumbnailer-master
AVFORMAT_INCLUDE_DIR
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master/test
AVFORMAT_LIBRARY
    linked by target "libffmpegthumbnailer" in directory /home/deploy/ffmpegthumbnailer-master
    linked by target "libffmpegthumbnailerstatic" in directory /home/deploy/ffmpegthumbnailer-master
AVUTIL_INCLUDE_DIR
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master
   used as include directory in directory /home/deploy/ffmpegthumbnailer-master/test
AVUTIL_LIBRARY
    linked by target "libffmpegthumbnailer" in directory /home/deploy/ffmpegthumbnailer-master
    linked by target "libffmpegthumbnailerstatic" in directory /home/deploy/ffmpegthumbnailer-master
```

**Comment by dirkvdb** [comment]
you are probably missing the development files from ffmpeg

**Comment by tumayun** [comment]
I have installed ffmpeg, and I use the following command can be installed successfully, but not the latest version (master branch).
```shell
sudo apt-get install ffmpegthumbnailer
```

**Comment by dirkvdb** [comment]
You need the following packages to build from source:
libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev

**Comment by tumayun** [comment]
make error!

```shell
deploy:~/ffmpegthumbnailer-master$ cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_GIO=ON -DENABLE_THUMBNAILER=ON .
-- checking for module 'libavcodec'
--   found libavcodec, version 54.35.0
-- checking for module 'libavformat'
--   found libavformat, version 54.20.4
-- checking for module 'libavutil'
--   found libavutil, version 52.3.0
-- checking for module 'libavfilter'
--   found libavfilter, version 3.3.0
--
-- CONFIGURATION SUMMARY
-- png support          : enabled
-- jpeg support         : enabled
-- gio support          : enabled
-- register thumbnailer : enabled
-- unittests            : enabled
-- debug mode           : disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/deploy/ffmpegthumbnailer-master
deploy:~/ffmpegthumbnailer-master$ make
Scanning dependencies of target libffmpegthumbnailer
[  5%] Building CXX object CMakeFiles/libffmpegthumbnailer.dir/libffmpegthumbnailer/moviedecoder.cpp.o
/home/deploy/ffmpegthumbnailer-master/libffmpegthumbnailer/moviedecoder.cpp:31:31: fatal error: libavutil/display.h: No such file or directory
 #include <libavutil/display.h>
```

**Comment by dirkvdb** [comment]
I guess your ubuntu version of ffmpeg is tool old and does not contain the display.h header yet.
You would have to install ffmpeg 3.0 from source for this to work

**Comment by tumayun** [comment]
@dirkvdb Hi
Excuse me,I encountered the following error:
```shell
~/ffmpegthumbnailer-master$ make
make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libavformat.so', needed by `libffmpegthumbnailer.so.4.11.0'.  Stop.
make[1]: *** [CMakeFiles/libffmpegthumbnailer.dir/all] Error 2
make: *** [all] Error 2
```
How should I fix it?

**Comment by tumayun** [comment]
@dirkvdb Hi, Can you help me?

**Comment by dirkvdb** [comment]
I need more ouput then what you pasted here

**Comment by tumayun** [comment]
@dirkvdb No more output.
Can you tell me how do you install FFmpeg 3.0 and ffmpegthumbnailer？
I need all commands and my OS is Ubuntu 14.04.

Thank you very much!

**Comment by dirkvdb** [comment]
There has te be more output if you start clean.

**Comment by gregatcode** [comment]
Great! Please, can we have some information on when new release is planned? Generally interested in this fix.

**Comment by dirkvdb** [comment]
I released a new version that contains the rotation fix

**Comment by gregatcode** [comment]
Thanks! I've built it, but it is giving
`Failed to get buffer from filter Resource temporarily unavailable. Smart frame selection failed. Retrying without smart frame detection.
Error: Failed to get buffer from filter Resource temporarily unavailable`
for every file i try

**Comment by dirkvdb** [comment]
mmm, can you provide a failing file, I cannot reproduce that behavior

**Comment by gregatcode** [comment]
For example: https://drive.google.com/open?id=0B2UtGIO3Tw5EYTdhbU5lWmU4M1U

Also, `make test` is reporting
> The following tests FAILED:
>        	  1 - ffmpegthumbnailertest (Failed)
> Errors while running CTest
> *** Error code 8
Built under FreeBSD 10.2-RELEASE-p18

**Comment by dirkvdb** [comment]
I'm not getting any errors on that file, what's yout ffmpeg version?

**Comment by gregatcode** [comment]
> ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100

**Comment by dirkvdb** [comment]
I'm testing with the latest 3.1.2 release, could be an issue in the older ffmpeg version. I will try to reproduce it against 2.7 when I have the opportunity.

**Comment by dirkvdb** [comment]
I just pushed a fix that should work again with ffmpeg older than v3

**Comment by gregatcode** [comment]
Works fine, thanks a lot!

**Comment by gregatcode** [comment]
Please, can you make a release with this fix?

**Comment by dirkvdb** [comment]
I'll try to make a release this weekend

**Comment by pinpox** [comment]
Was this ever fixed? Still getting rotated jpgs when creating thumbnails
